# Generated by Django 4.1.6 on 2023-02-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('Exchange', models.CharField(max_length=3)),
                ('Symbol', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Shortname', models.CharField(max_length=50)),
                ('Longname', models.CharField(max_length=100)),
                ('Sector', models.CharField(max_length=50)),
                ('Industry', models.CharField(max_length=100)),
                ('Currentprice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Marketcap', models.PositiveBigIntegerField()),
                ('Ebitda', models.BigIntegerField(blank=True, null=True)),
                ('Revenuegrowth', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(blank=True, max_length=2, null=True)),
                ('Country', models.CharField(max_length=50)),
                ('Fulltimeemployees', models.PositiveIntegerField()),
                ('Longbusinesssummary', models.TextField(max_length=5000)),
                ('Weight', models.DecimalField(decimal_places=8, max_digits=19)),
            ],
            options={
                'ordering': ['Symbol'],
            },
        ),
    ]
