# Generated by Django 4.1.6 on 2023-02-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exchange', models.CharField(max_length=3)),
                ('Symbol', models.CharField(max_length=5)),
                ('Shortname', models.CharField(max_length=50)),
                ('Longname', models.CharField(max_length=100)),
                ('Sector', models.CharField(max_length=50)),
                ('Industry', models.CharField(max_length=100)),
                ('Currentprice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Marketcap', models.PositiveBigIntegerField()),
                ('Ebitda', models.BigIntegerField(blank=True)),
                ('Revenuegrowth', models.DecimalField(decimal_places=4, max_digits=8)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(blank=True, max_length=2)),
                ('Country', models.CharField(max_length=50)),
                ('Fulltimeemployees', models.PositiveIntegerField()),
                ('Longbusinesssummary', models.TextField(max_length=300)),
                ('Weight', models.DecimalField(decimal_places=8, max_digits=19)),
            ],
        ),
    ]
