# Generated by Django 4.1.6 on 2023-02-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='id',
        ),
        migrations.AlterField(
            model_name='company',
            name='Symbol',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
