# Generated by Django 4.1.6 on 2023-02-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_company_id_alter_company_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Ebitda',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='State',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
